import { lookup } from "node:dns/promises";
import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";
export const maxDuration = 30;

const SOCIAL_PROCESSOR_HOSTS = ["youtube.com","youtu.be","tiktok.com","instagram.com","facebook.com","fb.watch","twitter.com","x.com"];
const DIRECT_EXTENSIONS = [".mp4",".webm",".mov",".m4v",".avi",".mkv",".mp3",".m4a",".ogg",".wav"];
const MAX_HTML_BYTES = 1_200_000;
const RATE_WINDOW_MS = 60_000;
const RATE_LIMIT = 20;
const rateBuckets = new Map<string,{count:number;resetAt:number}>();

function clientKey(req: NextRequest) { return (req.headers.get("x-forwarded-for") || req.headers.get("x-real-ip") || "anonymous").split(",")[0].trim(); }
function isRateLimited(req: NextRequest) { const now=Date.now(), key=clientKey(req), current=rateBuckets.get(key); if(!current || current.resetAt<=now){rateBuckets.set(key,{count:1,resetAt:now+RATE_WINDOW_MS});return false;} current.count+=1; return current.count>RATE_LIMIT; }
function isPrivateIpv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some((n)=>Number.isNaN(n)||n<0||n>255))return false;const[a,b]=p;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127);}
function isPrivateIpv6(ip:string){const v=ip.toLowerCase();return v==="::1"||v==="::"||v.startsWith("fc")||v.startsWith("fd")||/^fe[89ab]/.test(v);}
async function assertSafeUrl(raw:string){let parsed:URL;try{parsed=new URL(raw);}catch{throw new Error("Enter a valid http or https URL.");}if(!["http:","https:"].includes(parsed.protocol))throw new Error("Only http and https links are supported.");if(parsed.username||parsed.password)throw new Error("Links with embedded credentials are not allowed.");if(parsed.port&&!["80","443"].includes(parsed.port))throw new Error("Non-standard ports are not allowed.");const host=parsed.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(host==="localhost"||host.endsWith(".localhost")||host.endsWith(".local")||host==="metadata.google.internal"||isPrivateIpv4(host)||isPrivateIpv6(host))throw new Error("That network address is not allowed.");try{const addresses=await lookup(host,{all:true,verbatim:true});if(addresses.some(({address,family})=>family===4?isPrivateIpv4(address):isPrivateIpv6(address)))throw new Error("That network address is not allowed.");}catch(error){if(error instanceof Error&&error.message.includes("not allowed"))throw error;}return parsed;}
function hostnameMatches(host:string,root:string){return host===root||host.endsWith(`.${root}`);} function needsProcessor(url:URL){return SOCIAL_PROCESSOR_HOSTS.some((root)=>hostnameMatches(url.hostname.toLowerCase(),root));}
async function fetchWithSafeRedirects(input:string,init:RequestInit,maxRedirects=5){let current=input;for(let i=0;i<=maxRedirects;i+=1){await assertSafeUrl(current);const response=await fetch(current,{...init,redirect:"manual",cache:"no-store"});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)return{response,finalUrl:current};current=new URL(location,current).toString();continue;}return{response,finalUrl:current};}throw new Error("Too many redirects.");}
function looksDirect(url:URL,contentType=""){const path=url.pathname.toLowerCase();return contentType.startsWith("video/")||contentType.startsWith("audio/")||DIRECT_EXTENSIONS.some((ext)=>path.endsWith(ext));}
function extFromUrl(raw:string,fallback="mp4"){try{return new URL(raw).pathname.match(/\.([a-z0-9]{2,5})$/i)?.[1]||fallback;}catch{return fallback;}}
function safeFilename(title:string,ext:string){const base=(title||"video").replace(/[\\/:*?"<>|\u0000-\u001f]/g," ").replace(/\s+/g," ").trim().slice(0,100)||"video";return`${base}.${ext}`;}
function decodeHtml(value:string){return value.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
function attrFromTag(tag:string,name:string){return tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,"i"))?.[1]||"";}
function extractMeta(html:string,pageUrl:URL){const title=decodeHtml(html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:title["']/i)?.[1]||html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1]||"Video").trim();const thumbnail=decodeHtml(html.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i)?.[1]||"");const candidates=new Set<string>();for(const key of["og:video","og:video:url","og:video:secure_url","twitter:player:stream"]){const escaped=key.replace(":","\\:");for(const re of[new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["']`,"ig"),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["']`,"ig")])for(const match of html.matchAll(re))candidates.add(decodeHtml(match[1]));}for(const tag of html.match(/<(?:video|source)\b[^>]*>/gi)||[]){const src=attrFromTag(tag,"src");if(src)candidates.add(decodeHtml(src));}const normalized=[...candidates].map((c)=>{try{return new URL(c,pageUrl).toString();}catch{return"";}}).filter(Boolean);let resolvedThumbnail="";if(thumbnail){try{resolvedThumbnail=new URL(thumbnail,pageUrl).toString();}catch{}}return{title,thumbnail:resolvedThumbnail,candidates:normalized};}
async function readBoundedText(response:Response,limit:number){const reader=response.body?.getReader();if(!reader)return"";const chunks:Uint8Array[]=[];let total=0;while(total<limit){const{done,value}=await reader.read();if(done)break;if(!value)continue;const remaining=limit-total,chunk=value.length>remaining?value.slice(0,remaining):value;chunks.push(chunk);total+=chunk.length;if(value.length>remaining)break;}try{await reader.cancel();}catch{}const merged=new Uint8Array(total);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.length;}return new TextDecoder().decode(merged);}
async function callConfiguredProcessor(url:string,quality:string,mode:string){const processorUrl=process.env.MEDIA_PROCESSOR_URL?.trim();if(!processorUrl)return null;const headers:Record<string,string>={Accept:"application/json","Content-Type":"application/json"};const key=process.env.MEDIA_PROCESSOR_API_KEY?.trim();if(key)headers.Authorization=`Api-Key ${key}`;const response=await fetch(processorUrl,{method:"POST",headers,cache:"no-store",body:JSON.stringify({url,videoQuality:quality||"1080",downloadMode:mode==="audio"?"audio":"auto",audioFormat:"mp3",filenameStyle:"pretty",youtubeVideoCodec:"h264",alwaysProxy:false})});const data=await response.json().catch(()=>null);if(!response.ok||!data)throw new Error(`Media processor returned ${response.status}.`);if(data.status==="error")throw new Error(data?.error?.code||"Media processor could not resolve that link.");if(data.status==="tunnel"||data.status==="redirect")return{ok:true,source:"processor",items:[{type:mode==="audio"?"audio":"video",url:data.url,filename:data.filename||safeFilename("download",mode==="audio"?"mp3":"mp4")}]};if(data.status==="picker"){const items:Array<{type:string;url:string;thumbnail?:string;filename:string}>=Array.isArray(data.picker)?data.picker.map((item:Record<string,string>,index:number)=>({type:item.type||"video",url:item.url,thumbnail:item.thumb||"",filename:safeFilename(`download-${index+1}`,item.type==="photo"?"jpg":item.type==="gif"?"gif":"mp4")})):[];if(data.audio)items.push({type:"audio",url:data.audio,filename:data.audioFilename||"audio.mp3"});return{ok:true,source:"processor",items};}throw new Error("Media processor returned an unsupported response.");}
async function genericResolve(inputUrl:string){const input=await assertSafeUrl(inputUrl);try{const{response:head,finalUrl}=await fetchWithSafeRedirects(input.toString(),{method:"HEAD",headers:{"User-Agent":"Mozilla/5.0 BigSignalTools/1.0"}});const finalParsed=await assertSafeUrl(finalUrl),contentType=(head.headers.get("content-type")||"").toLowerCase();if(head.ok&&looksDirect(finalParsed,contentType)){const ext=extFromUrl(finalUrl,contentType.includes("webm")?"webm":contentType.startsWith("audio/")?"mp3":"mp4");return{ok:true,source:"direct",title:"Direct media file",items:[{type:contentType.startsWith("audio/")?"audio":"video",url:finalUrl,filename:safeFilename("download",ext)}]};}}catch{}const{response,finalUrl}=await fetchWithSafeRedirects(input.toString(),{method:"GET",headers:{"User-Agent":"Mozilla/5.0 (compatible; BigSignalTools/1.0)",Accept:"text/html,video/*;q=0.9,*/*;q=0.8"}});if(!response.ok)throw new Error(`Source returned HTTP ${response.status}.`);const finalParsed=await assertSafeUrl(finalUrl),contentType=(response.headers.get("content-type")||"").toLowerCase();if(looksDirect(finalParsed,contentType)){const ext=extFromUrl(finalUrl,contentType.includes("webm")?"webm":contentType.startsWith("audio/")?"mp3":"mp4");return{ok:true,source:"direct",title:"Direct media file",items:[{type:contentType.startsWith("audio/")?"audio":"video",url:finalUrl,filename:safeFilename("download",ext)}]};}if(!contentType.includes("text/html")&&!contentType.includes("application/xhtml+xml"))throw new Error("The link did not return a video or a webpage containing a public media source.");const meta=extractMeta(await readBoundedText(response,MAX_HTML_BYTES),finalParsed),items:{type:string;url:string;filename:string}[]=[];for(const candidate of meta.candidates.slice(0,12)){try{const parsed=await assertSafeUrl(candidate);const{response:candidateHead,finalUrl:resolved}=await fetchWithSafeRedirects(parsed.toString(),{method:"HEAD",headers:{"User-Agent":"Mozilla/5.0 BigSignalTools/1.0"}},3);const candidateType=(candidateHead.headers.get("content-type")||"").toLowerCase();if(candidateHead.ok&&looksDirect(new URL(resolved),candidateType)){const ext=extFromUrl(resolved,candidateType.includes("webm")?"webm":candidateType.startsWith("audio/")?"mp3":"mp4");items.push({type:candidateType.startsWith("audio/")?"audio":"video",url:resolved,filename:safeFilename(meta.title,ext)});}}catch{}}const unique=[...new Map(items.map((item)=>[item.url,item])).values()];if(!unique.length)throw new Error("No directly downloadable public media was found on that page.");return{ok:true,source:"page",title:meta.title,thumbnail:meta.thumbnail,items:unique};}

export async function POST(req:NextRequest){const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};if(isRateLimited(req))return NextResponse.json({ok:false,error:"Too many requests. Try again in a minute."},{status:429,headers});try{const body=await req.json().catch(()=>({})),inputUrl=String(body?.url||"").trim(),quality=String(body?.quality||"1080"),mode=body?.mode==="audio"?"audio":"video";if(!inputUrl)return NextResponse.json({ok:false,error:"Paste a video URL first."},{status:400,headers});if(inputUrl.length>2048)return NextResponse.json({ok:false,error:"That URL is too long."},{status:400,headers});const parsed=await assertSafeUrl(inputUrl),processor=await callConfiguredProcessor(parsed.toString(),quality,mode);if(processor)return NextResponse.json(processor,{status:200,headers});if(needsProcessor(parsed))return NextResponse.json({ok:false,code:"processor_required",error:"This social platform needs the dedicated media processor. The site is ready for it, but the processor endpoint has not been connected yet."},{status:422,headers});return NextResponse.json(await genericResolve(parsed.toString()),{status:200,headers});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Unable to process that link."},{status:400,headers});}}
