export type Platform = { slug: string; name: string; title: string; description: string; intro: string; tips: string[] };

export const platforms: Platform[] = [
  { slug: "youtube-video-downloader", name: "YouTube", title: "YouTube Video Downloader — Save Authorized Videos Online", description: "Use our YouTube video downloader to process public videos you own or are authorized to save. Fast, mobile-friendly workflow with clear quality choices.", intro: "Paste a YouTube link for media you created, own, licensed, or otherwise have permission to save.", tips: ["Use the original watch or Shorts URL.", "Available quality depends on the source and processor.", "Protected or DRM-restricted content is not supported."] },
  { slug: "facebook-video-downloader", name: "Facebook", title: "Facebook Video Downloader — Download Authorized Videos", description: "Process public Facebook video links you are authorized to save with a clean, mobile-friendly downloader experience.", intro: "Use a public Facebook video URL for media you own or have permission to download.", tips: ["Public video links are the most reliable.", "Private or login-only media may not be available.", "Respect uploader rights and platform rules."] },
  { slug: "instagram-video-downloader", name: "Instagram", title: "Instagram Video Downloader — Reels & Video Saver", description: "Save public Instagram videos and Reels you own or are authorized to download using a simple online downloader.", intro: "Paste an Instagram Reel or video URL for content you are authorized to save.", tips: ["Public Reel and video links work best.", "Private-account content is not supported.", "Only save content when you have the required rights."] },
  { slug: "tiktok-video-downloader", name: "TikTok", title: "TikTok Video Downloader — Save Authorized TikTok Videos", description: "Process public TikTok video links you own or have authorization to save. Fast workflow for mobile and desktop.", intro: "Paste a TikTok video URL for media you own or have permission to download.", tips: ["Use the canonical TikTok video link when possible.", "Availability can depend on the source post.", "Respect creator rights and platform rules."] },
  { slug: "x-video-downloader", name: "X / Twitter", title: "X Video Downloader — Download Authorized Twitter Videos", description: "Use our X / Twitter video downloader for public media you own or are permitted to save.", intro: "Paste an X post URL containing a video you are authorized to save.", tips: ["Public post URLs work best.", "Some media requires the dedicated processor.", "Only download content you have rights to use."] },
  { slug: "vimeo-video-downloader", name: "Vimeo", title: "Vimeo Video Downloader — Save Authorized Vimeo Videos", description: "Process public Vimeo video links you own or are authorized to download with clear quality and device support.", intro: "Paste a Vimeo video URL for content you own, licensed, or have permission to save.", tips: ["Use the public video page URL.", "Available qualities depend on the source.", "Creator download restrictions still apply."] },
];

export const platformBySlug = Object.fromEntries(platforms.map((p) => [p.slug, p])) as Record<string, Platform>;

export type InfoPage = { title: string; description: string; sections: [string, string][] };
export const infoPages: Record<string, InfoPage> = {
  about: { title: "About BigSignal Tools", description: "A cleaner media utility focused on speed, clarity, mobile usability, and responsible downloading.", sections: [["What we built", "BigSignal Tools is designed to make authorized media saving straightforward: paste a public link, resolve an available media file, and use your browser or device controls to save it."], ["What makes it different", "The interface keeps advertising visually separate from download controls, avoids fake download buttons, and is designed to work cleanly on phones, tablets, and desktop browsers."], ["Responsible use", "The service is intended for media you own, created, licensed, or otherwise have permission or legal authorization to save. It is not designed to bypass DRM or access controls."]] },
  privacy: { title: "Privacy Policy", description: "How BigSignal Tools handles submitted URLs, technical data, analytics, and advertising.", sections: [["Links you submit", "A submitted URL is sent to the media-resolution backend so the service can determine whether a public media file is available. The service does not require a video upload when a public source link is sufficient."], ["Technical data", "Hosting and security systems may process basic technical information such as IP address, browser type, request time, and diagnostic logs for abuse prevention, reliability, and security."], ["Analytics and advertising", "If analytics or advertising services are enabled, those providers may use cookies or similar technologies according to their own policies and applicable consent requirements. Advertising remains visually distinct from downloader controls."], ["Data minimization", "The service is designed to avoid collecting personal information that is not needed to provide, secure, measure, or improve the downloader."]] },
  terms: { title: "Terms of Use", description: "Rules for using BigSignal Tools responsibly and lawfully.", sections: [["Authorized use only", "You may use this service only for content you own or have permission or legal authorization to download. You are responsible for complying with copyright law, contractual restrictions, and source-platform rules."], ["No protected-content bypass", "The service is not offered for bypassing DRM, authentication, paywalls, access controls, or other technical protection measures."], ["Service availability", "Media websites frequently change their technical systems. A source that works today may fail later, and available quality or format options can vary."], ["Abuse prevention", "Automated abuse, excessive requests, malicious URLs, or attempts to reach private network resources may be blocked."]] },
  copyright: { title: "Copyright & Removal", description: "Information for rights holders and users about responsible media downloading.", sections: [["User responsibility", "Users are instructed to download only media they own or are authorized to save. The service does not grant rights to third-party content."], ["No media library", "The downloader is a link-processing utility, not a catalog or repository of third-party videos. When possible, media remains hosted by the original source or configured processing service."], ["Rights-holder concerns", "If you believe a page on this service unlawfully promotes or exposes specific copyrighted material, contact the site operator with the affected URL, identification of the work, your contact information, and a clear explanation of the issue."]] },
  contact: { title: "Contact", description: "Contact BigSignal Tools about product, privacy, or rights-holder concerns.", sections: [["Product and support", "For product support, include the page URL, source platform, device/browser, and the exact error message you saw. Do not send passwords, private media, or account credentials."], ["Copyright and rights-holder requests", "For rights-holder requests, identify the copyrighted work, the affected BigSignal Tools URL, your relationship to the rights holder, and enough contact information to respond."]] },
};

export const dynamicSlugs = [...platforms.map((p) => p.slug), "privacy", "terms", "copyright"];
export const allSiteSlugs = [...platforms.map((p) => p.slug), ...Object.keys(infoPages)];
